# ビルドのたびに実行し、実行ファイルに git の版を埋め込むヘッダを生成する(dw-notes「版を名乗る」方針 2026-08-22)
# 形式: <branch>@<short hash>[+dirty]。detached なら HEAD@<hash>。git が無ければ "unknown (no git)"
# パッケージ直下に空の .git が居ることがある(monorepo の wada_vmc で実例)ので、失敗したら親へ最大 6 段さかのぼる
set(DIR "${SRC_DIR}")
set(V "")
foreach(i RANGE 6)
  execute_process(COMMAND git -C "${DIR}" rev-parse --short HEAD
    OUTPUT_VARIABLE H OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE R ERROR_QUIET)
  if(R EQUAL 0 AND NOT "${H}" STREQUAL "")
    execute_process(COMMAND git -C "${DIR}" rev-parse --abbrev-ref HEAD
      OUTPUT_VARIABLE B OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if("${B}" STREQUAL "")
      set(B "HEAD")
    endif()
    execute_process(COMMAND git -C "${DIR}" status --porcelain -- "${SRC_DIR}"
      OUTPUT_VARIABLE D OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    set(V "${B}@${H}")
    if(NOT "${D}" STREQUAL "")
      set(V "${V}+dirty")
    endif()
    break()
  endif()
  get_filename_component(DIR "${DIR}" DIRECTORY)
endforeach()
if("${V}" STREQUAL "")
  set(V "unknown (no git)")
endif()
set(CONTENT "#pragma once\n#define DW_VERSION \"${V}\"\n")
set(OLD "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" OLD)
endif()
if(NOT "${OLD}" STREQUAL "${CONTENT}")
  file(WRITE "${OUT}" "${CONTENT}")
endif()
